name: incu
channels:
  - conda-forge
dependencies:
  - numpy
  - ipykernel
  - tqdm
  - ca-certificates
  - openssl
  - pandas
  - nbgitpuller
  - matplotlib
  - pip:
      - langdetect
prefix: C:\Users\HLloyd\AppData\Local\mambaforge\envs\incu
